okta:
  OKTA_AUTH_URL: "Okta auth URL"
  OKTA_CLIENT_ID: "Okta client ID"
  OKTA_ENDPOINTS: [ 'admin' ]
llm:
  LLM_API: "your LLM api server" # https://api.openai.com/v1"
  AUTH_KEY: "your api key"
  QA_MODEL: "default QA model" #mistralai/Mixtral-8x7B-Instruct-v0.1"
  QA_MODEL_MAX_TOKEN_LIMIT: "max token limit for QA model" #30000
  SUMMARIZE_MODEL: "default model for summarization task" #"meta-llama/Meta-Llama-3-70B-Instruc"
  EMBEDDING_MODEL: "embedding model" #"Salesforce/SFR-Embedding-Mistral"
  VECTOR_DIM: "embedding model vector dimension" #4096
  MAX_COMPLETION: "max tokens of completion for each query" #700
  CHUNK_SIZE: "default chunk size" #512
  CHUNK_OVERLAP: "default chunk overlap" # 20
  NUM_QUERIES: "default number of queries" #10
  TOP_K: 5
  LLM_BATCH_SIZE: 1
  AUDIO_API: "stt-service URL" #"http://localhost:9000/api/v1"
database:
  PG_HOST: "Database host" #"localhost"
  PG_PORT: 5432
  PG_USER: DB_USER
  PG_PASSWD: DB_PASSWORD
  PG_DATABASE: "vectordb"
  PG_TABLE: "embeddings"
  PG_VECTOR_DIM: 4096 # match the vector dimension of the embedding model
# server configuration
server:
  HOST: "0.0.0.0"
  PORT: 5000
  NUM_WORKERS: 1
  PDF_READER: pypdf # default PDF parser
  FILE_PATH:  "../data"
  RELOAD: False
  VECTOR_DB: pgvector 
email:
  SMTP_SERVER: "email server"
  SENDER: "send email"
  SUMMARIZER_URL: "Summarizer Client URL" # "http://localhost:4200"
  


