okta:
  OKTA_AUTH_URL: "Okta auth URL"
  OKTA_CLIENT_ID: "Okta client ID"
  OKTA_ENDPOINTS: [ 'admin' ]
llm:
  LLM_API: "your LLM api server" # https://api.openai.com/v1"
  AUTH_KEY: "your openai api key"
  QA_MODEL: "default QA model" #mistralai/Mixtral-8x7B-Instruct-v0.1"
  QA_MODEL_MAX_TOKEN_LIMIT: "max token limit for QA model" #30000
  EMBEDDING_MODEL: "embedding model" #"Salesforce/SFR-Embedding-Mistral"
  VECTOR_DIM: "embedding model vector dimension" #4096
  SIMIL_TOP_K: 10 # Retrieve TOP_K most similar docs from the PGVector store
  RERANK_ENABLED: True
  RERANK_MODEL: "BAAI/bge-reranker-large" # re-ranking model
  RERANK_TOP_N: 5 # Rerank and pick the 5 most similar docs
  MAX_COMPLETION: 700 # max tokens of completion for each query
  CHUNK_SIZE: 512 # default chunk size
  CHUNK_OVERLAP: 20 # default chunk overlap
  NUM_QUERIES: 3 # default number of queries
  TOP_K: 5
  LLM_BATCH_SIZE: 1
database:
  PG_HOST: "Database host" #"localhost"
  PG_PORT: 5432
  PG_USER: DB_USER
  PG_PASSWD: DB_PASSWORD
  PG_DATABASE: "vectordb"
  PG_TABLE: "embeddings"
  PG_VECTOR_DIM: 4096 # match the vector dimension of the embedding model
# server configuration
server:
  HOST: "0.0.0.0"
  PORT: 5000
  NUM_WORKERS: 1
  PDF_READER: pypdf # default PDF parser
  FILE_PATH:  "../data"
  RELOAD: False
  VECTOR_DB: pgvector 
stt:
  STT_API: "http://localhost:9000/api/v1" # STT-server URL
  AUTH_KEY: "your STT api auth key"
email:
  SMTP_SERVER: "email server"
  SENDER: "send email"
  SUMMARIZER_URL: "Summarizer Client URL" # "http://localhost:4200"
  


