services:
  db:
    image: pgvector/pgvector:pg12
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=demopasswd
      # - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data:/var/lib/postgresql/data
